insert into event (name) values ('Apply');
insert into event (name) values ('Phone Interview');
insert into event (name) values ('Tour');
insert into event (name) values ('Problem Solving Challenge');
insert into event (name) values ('Behavioral Interview');
insert into event (name) values ('Command Line Review');
insert into event (name) values ('Command Line Assessment');
insert into event (name) values ('Pre Work');
insert into event (name) values ('Pre Work Assessment');
insert into event (name) values ('Accepted');
